### ISSUE TITLE
README.md incomplete

### ISSUE THREAD

**Issue by puchrojo** [rmoriz/hetzner-bootstrap#4]
Hallo,
Ich denke die README.md ist nicht ausführlich genüg. 
Env. Variables sind Richtig gesetzt, da diese Skript lauft:
$ curl -u $ROBOT_USER:$ROBOT_PASSWORD https://robot-ws.your-server.de/boot/176.9.25.XXXX

Die gem install hetzner-bootstrap als root geht ohne Fehler. 

Nur hier bekommt man ein Fehler:
$ chmod +x ./example.rb
$ ./example.rb
...
[enable_rescue_mode] rescue system could not be activated
something bad happened unexpectedly: Hetzner::Bootstrap::Target::CantActivateRescueSystemError => {"error"=>{"status"=>401, "code"=>"UNAUTHORIZED", "message"=>"Unauthorized"}}

Hier das ende meine example.rb
bs << { :ip => "176.9.25.XXXX",
        :template => template,                 # string will be parsed by erubis  
        :hostname => 'server1.mydomain.com',  # will be used for setting the systems' hostname  
        :public_keys => "~/.ssh/id_rsa_PR.pub",   # will be copied over to the freshly bootstrapped system  
        :post_install => post_install }        # will be called locally at the end and can be used e.g. to run a chef bootstrap 

Mit freundlichen Grüßen,
Isaac Puch

**Comment by rmoriz** [comment]
Please post your complete example.rb, also don't install/run ruby or rubygems via root.

Von meinem iPhone gesendet

**Comment by rmoriz** [comment]
works for me
